import Head from "next/head";
import Image from "next/image";

import {
  Box,
  Container,
  Heading,
  Text,
  Divider,
  useColorMode,
} from "@chakra-ui/react";
import { FormForgotPassword, FormInputOtp, FormResetPassword } from "../form";
import { useRouter } from "next/router";

export default function Login() {
  const router = useRouter();
  const { email, otp } = router.query;
  return (
    <div>
      <Head>
        <title>E-ROR | Lupa Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxWidth="100%"
        height="100vh"
        display="flex"
        justifyContent="center"
        alignItems="center"
      >
        <Box
          display="flex"
          alignItems="center"
          borderRadius="md"
          boxShadow={["", "", "", "xl"]}
          h={["100%", "100%", "100%", "2xl"]}
          w={["100%", "100%", "100%", "75%"]}
          position="relative"
        >
          <Box
            height="100%"
            borderRadius="md"
            width="50%"
            display={["none", "none", "none", "inline", "inline", "inline"]}
            p="12"
            position="relative"
            zIndex="500"
          >
            <Box
              as="object"
              type="image/svg+xml"
              data={
                !email && !otp
                  ? "/assets/svg/forget.svg"
                  : !otp
                  ? "/assets/svg/otp.svg"
                  : "assets/svg/password.svg"
              }
              maxW="100%"
              height="96"
            ></Box>
            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              flexDir="column"
              textAlign="center"
            >
              <Heading
                fontSize="1.7em"
                color={
                  useColorMode().colorMode === "dark" ? "gray.100" : "gray.900"
                }
                fontWeight="bold"
              >
                {!email && !otp
                  ? "Lupa password?"
                  : !otp
                  ? "Cek email anda!"
                  : "Ubah password"}
              </Heading>
              <Text mt="3" color="gray.600" fontWeight="semibold">
                {!email && !otp
                  ? "Jangan khawatir! Anda dapat me-reset password anda dengan memasukan email akun pada."
                  : !otp
                  ? "Kode OTP telah terkirim. Mohon cek email anda dan masukan kode nya kesini."
                  : "Pastikan password anda telah benar dan telah diingat agar tidak terulang lagi."}
              </Text>
            </Box>
          </Box>
          <Box w={["100%", "100%", "100%", "50%"]} mx="auto" my="40" p="10">
            <Heading as="h1" size="lg">
              {!email && !otp
                ? "Konfirmasi email."
                : !otp
                ? "Verifikasi kode OTP"
                : "Reset password"}
            </Heading>
            <Divider mt="5" mb="5" />
            {!email && !otp ? (
              <FormForgotPassword />
            ) : !otp ? (
              <FormInputOtp />
            ) : (
              <FormResetPassword />
            )}
          </Box>
        </Box>
      </Container>
    </div>
  );
}
